#!/bin/bash

# List available drives
fdisk -l

# Prompt user to input the drive to partition
read -p "Enter the drive to partition (e.g. /dev/sda): " drive

# Create new partition table
sudo sfdisk --label gpt "$drive" << EOF
,550M,U,*
,2G,S
,,L
EOF

# Format partitions
sudo mkfs.fat -F32 /dev/sda1
sudo mkswap /dev/sda2
sudo mkfs.ext4 /dev/sda3

# Enable swap
sudo swapon /dev/sda2
